name: Verify Live Trading
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select API Module to Test'
        required: true
        default: 'market'
        type: choice
        options:
          - market
          - limit
          - stop
          - stop_limit
          - management

jobs:
  test-live-trade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Execute T212 Module
        env:
          T212_API_KEY: ${{ secrets.T212_API_Trade_Key }}
          T212_API_SECRET: ${{ secrets.T212_API_Trade_Secret }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          case "${{ github.event.inputs.test_type }}" in
            "market") python activate_live.py ;;
            "limit") python test_limit_order.py ;;
            "stop") python test_stop_order.py ;;
            "stop_limit") python test_stop_limit_order.py ;;
            "management") python test_order_manage.py ;;
          esac
